spring:
  application:
    name: leaveManagement
  datasource:
    url: ${DBMS_CONNECTION:jdbc:sqlserver://localhost:1433;databaseName=leave_management;encrypt=true;trustServerCertificate=true}
    username: ${DBMS_USERNAME:sa}
    password: ${DBMS_PASSWORD:Quyet@123}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        connection:
          CharSet: utf8
          characterEncoding: UTF-8
          useUnicode: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_NAME_MAIL_SENDER}
    password: ${PASSWORD_MAIL_SENDER}
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8081
  servlet:
    context-path: ${CONTEXT_PATH:/api}

# config secret key
jwt:
  access-token-signer-key: ${ACCESS_TOKEN:dbVkYCHQIBx33giGxnJic7noT0eagNcR}
  refresh-token-signer-key: ${REFRESH_TOKEN:Wu8w4pkiVmErS9Z9Loel7tMBM7f3VFjD}
  access-token-duration: ${ACCESS_TOKEN_DURATION:540} # in second
  refresh-token-duration: ${REFRESH_TOKEN:600} # in second
logging:
  level:
    org:
      springframework:
        web:
          cors: DEBUG